OGGBundle: handle filepaths with non ascii characters.
This fixes the following UnicodeEncodeError which has been raised when
importing files with umlauts in the filepath.

```
  File ".../fileloader.py", line 194, in get_abs_filepath
    abs_filepath = self.build_absolute_filepath(_filepath)
  File ".../fileloader.py", line 148, in build_absolute_filepath
    filepath = self._translate_unc_path(filepath)
  File ".../fileloader.py", line 140, in _translate_unc_path
    abs_filepath = os.path.join(posix_mountpoint, relative_path)
  File "..python2.7/posixpath.py", line 71, in join
    path +=  b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
```